default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: morney
  password: 123456
  host: localhost
  port: 5001

development:
  <<: *default
  database: rails_demo3_development
test:
  <<: *default
  database: rails_demo3_test
production:
  <<: *default
  database: rails_demo3_production
  username: rails_demo3
  password: <%= ENV['MORNEY_RAILS_1_DATABASE_PASSWORD'] %>